### ISSUE TITLE
Live Server

### ISSUE THREAD

**Issue by wilsonhws** [AxelAli/Tensorflow-Image-Classifier-Web-Demo#2]
Hi, how to upload this project to a live server? I have a virtual machine running on google cloud atm.

**Comment by AxelAli** [comment]
Use Flask or Similar .
Heroku.com as well

**Comment by VD2410** [comment]
hello sir , I am getting this error while running in xampp server.
classifier is working correctly in Terminal
![screenshot from 2017-11-22 18-43-49](https://user-images.githubusercontent.com/23291670/33130176-7b4237a8-cfb8-11e7-9756-d0e21c6f0666.png)

**Comment by AxelAli** [comment]
Hello there!
Seems to be a problem with tensorflow itself.
[Here seems to be the answer](https://stackoverflow.com/questions/43558707/tensorflow-importerror-libcusolver-so-8-0-cannot-open-shared-object-file-no)

**Comment by VD2410** [comment]
No sir I am able to run code in terminal

**Comment by AxelAli** [comment]
Hello there!
`ImportError: libcusolver.so.8.0: cannot open shared object file: No such file or directory
`
is a problem with tensorflow, i suggest using flask. is as easy as it gets,
